name: Daily Video Agent
on:
  schedule:
    - cron: '00 19 * * *'  # Runs at 2:00 PM ET / 19:00 UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install System Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install moviepy==1.0.3 imageio==2.25.1 edge-tts Pillow==9.5.0 groq

      - name: Run Generator
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} 
        run: python -u generator.py

      - name: Commit and Push
        run: |
          git config --global user.name "AI Video Agent"
          git config --global user.email "agent@bot.com"
          git add daily_video.mp4
          git commit -m "New Daily Video Generated"
          git push
